baseURL = "https://crpg.info/"  # Change to https://[YOUR-ORG].github.io/crpg-website/ for testing
languageCode = "en-us"
title = "Center for Regulation, Policy and Governance"
theme = "ananke"  # Temporary theme, will be replaced with Hugo Blox
# Google Analytics moved to services section

# Custom CSS
[params.ananke_socials]
[params]
  custom_css = ["css/custom.css"]
  favicon = ""
  site_logo = ""
  description = "Center for Regulation, Policy and Governance - Research and policy analysis for sustainable development"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = true
  background_color_class = "bg-white"
  recent_posts_number = 3

  author = "CRPG Team"
  
# Menu configuration
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Profile"
  url = "/profile/"
  weight = 2

[[menu.main]]
  name = "Our Works"
  url = "/our-works/"
  weight = 3
  identifier = "our-works"

[[menu.main]]
  name = "Program"
  url = "/program/"
  parent = "our-works"
  weight = 1

[[menu.main]]
  name = "Events"
  url = "/events/"
  parent = "our-works"
  weight = 2

[[menu.main]]
  name = "Research"
  url = "/research/"
  parent = "our-works"
  weight = 3

[[menu.main]]
  name = "EHRDD"
  url = "/ehrdd/"
  parent = "our-works"
  weight = 4

[[menu.main]]
  name = "Gallery"
  url = "/gallery/"
  parent = "our-works"
  weight = 5

[[menu.main]]
  name = "Publications"
  url = "/publications/"
  weight = 4

[[menu.main]]
  name = "News"
  url = "/news/"
  weight = 5

[[menu.main]]
  name = "Team"
  url = "/team/"
  weight = 6

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 7

# Output formats
[outputFormats]
  [outputFormats.JSON]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  
# Permalinks
[permalinks]
  posts = "/:year/:month/:slug/"
  
# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
  topic = "topics"

# Build configuration
[build]
  writeStats = true
  
# Markup configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allow raw HTML in markdown
  [markup.highlight]
    codeFences = true
    lineNos = false
    noClasses = false
    style = "monokai"
    tabWidth = 2

# Security configuration
[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
  [security.funcs]
    getenv = ['^HUGO_']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']

# Services configuration
[services]
  [services.googleAnalytics]
    ID = ""  # Add your GA4 ID here when available